groups:
  Supervisor:
    - "Merhaba"
    - "Bana hangi konularda yardımcı olabilirsin."
  
  "Forza API":
    - "Forza ERP API bağlanır mısın?"
    - "Kullanıcı adı a@a.com ve şifre 1233"
    - "Bu kullanıcının tüm işletmelerini listele"
    - "Vega işletmesinin tüm şubelerini göster."
  
  "Master Raporlar":
    - "Master Raporlarda 'MERKEZ' şubesinin Temmuz 2025teki satışlarını kategori bazında görmek istiyorum."
    - "Şimdi bunların toplam tutarını ver."
    - "VEGA işletmesi için toplam ciro nedir?"
  
  Mevzuat:
    - "Restorantlarda ÖKC kullanımı ile ilgili yasa düzenleme göster."
    - "Bu düzenlemelerin kısaca açıkla" 
